=== ekleinod/opentt-documents/rules/rules.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
XSD Schema for an rules file

v0.2.0

Ekkart Kleinod
ekleinod@edgesoft.de
2014
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
						xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
						jxb:version="2.0">

	<xsd:element name="rules" type="RulesType"/>

	<xsd:complexType name="RulesType">
		<xsd:sequence>
			<xsd:element name="info" type="InfoType" minOccurs="1" maxOccurs="1" />
			<xsd:element name="rule" type="RuleType" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="InfoType">
		<xsd:sequence>
			<xsd:element name="creation" type="xsd:dateTime" minOccurs="1" maxOccurs="1" />
			<xsd:element name="lastchange" type="xsd:dateTime" minOccurs="1" maxOccurs="1" />
			<xsd:element name="version" type="VersionType" minOccurs="1" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="RuleType">
		<xsd:complexContent>
			<xsd:extension base="IDType">
				<xsd:sequence>
					<xsd:element name="rulecontent" type="RuleContentType" minOccurs="1" maxOccurs="unbounded" />
					<xsd:element name="rule" type="RuleType" minOccurs="0" maxOccurs="unbounded" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="RuleContentType">
		<xsd:complexContent>
			<xsd:extension base="LangType">
				<xsd:sequence>
					<xsd:element name="title" type="xsd:string" minOccurs="0" maxOccurs="1" />
					<xsd:element name="subtitle" type="xsd:string" minOccurs="0" maxOccurs="1" />
					<xsd:element name="para" type="TextWithLinksType" minOccurs="0" maxOccurs="unbounded" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="RefType">
		<xsd:attribute name="idref" type="xsd:IDREF" use="required">
			<xsd:annotation>
				<xsd:appinfo>
					<jxb:property>
						<jxb:baseType name="IDType"/>
					</jxb:property>
				</xsd:appinfo>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="IDType" abstract="true">
		<xsd:attribute name="id" type="xsd:ID" use="required" />
	</xsd:complexType>

	<xsd:complexType name="LangType" abstract="true">
		<xsd:attribute name="lang" type="xsd:language" use="required" />
	</xsd:complexType>

	<xsd:complexType name="ParasType">
		<xsd:sequence>
			<xsd:element name="para" type="TextWithLinksType" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="TextWithLinksType" mixed="true">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="rulesref" type="RefType" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="VersionType">
		<xsd:sequence>
			<xsd:element name="major" type="IntGreaterNull" minOccurs="1" maxOccurs="1" />
			<xsd:element name="minor" type="IntGreaterNull" minOccurs="1" maxOccurs="1" />
			<xsd:element name="patch" type="IntGreaterNull" minOccurs="1" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="IntGreaterNull">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="0" />
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

<!-- EOF -->

=== ekleinod/opentt-documents/rules/rules.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="reveal.xslt"?>

<rules
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="rules.xsd">

	<info>
		<creation>2014-10-20T00:26:00.000+02:00</creation>
		<lastchange>2014-10-20T00:26:00.000+02:00</lastchange>
		<version>
			<major>0</major>
			<minor>2</minor>
			<patch>0</patch>
		</version>
	</info>

	<rule id="Rules">
		<rulecontent lang="de">
			<title>Tischtennisregeln</title>
		</rulecontent>

		<rule id="Rules.B">
			<rulecontent lang="de">
				<title>Teil B</title>
				<subtitle>Bestimmungen für internationale Veranstaltungen (Auszug)</subtitle>
				<para>
					Die nachfolgenden Regeln und Bestimmungen der ITTF gelten, soweit nicht ausdrücklich anders festgelegt, für den Bereich des DTTB.
					Alle über diesen Rahmen hinausgehenden Bestimmungen dieses Abschnittes wurden nicht mit aufgenommen; sie können im Abschnitt 3 des ITTF-Handbuches nachgeschlagen werden.
				</para>
			</rulecontent>

			<rule id="Rules.B.2">
				<rulecontent lang="de">
					<title>Spielmaterial und Spielbedingungen</title>
				</rulecontent>
				<rule id="Rules.B.2.2">
					<rulecontent lang="de">
						<title>Spielkleidung</title>
					</rulecontent>
					<rule id="Rules.B.2.2.8">
						<rulecontent lang="de">
							<para>
								Während eines Mannschaftskampfes müssen die daran teilnehmenden Spieler einer Mannschaft einheitlich gekleidet sein.
								Das gleiche gilt bei Welt-, Olympischen und Paralympischen Titelwettbewerben für die Spieler eines Doppels, sofern sie dem gleichen Verband angehören.
								Von dieser Bestimmung können Socken, Schuhe sowie Anzahl, Größe, Farbe und Design von Werbung auf der Spielkleidung ausgenommen werden.
								Spieler desselben Verbands, die bei anderen internationalen Veranstaltungen ein Doppel bilden, können Kleidung verschiedener Hersteller tragen, falls die Grundfarben gleich sind und ihr Nationalverband dieses Verfahren genehmigt.
							</para>
						</rulecontent>
					</rule>
				</rule>
			</rule>
		</rule>

	</rule>

</rules>
